### ISSUE TITLE
Tags from metrics name

### ISSUE THREAD

**Issue by surik** [travelping/exometer_influxdb#3]
Exometer doesn't support tags in metric name.

Lets we have metics:

```
[eradius, '127.0.0.1:8111', requests]
[eradius, '127.0.0.1:9222', requests]
```

And we want to see it in InfluxDB like this:

```
eradius_requests, nas=127.0.0.1:8111
eradius_requests, nas=127.0.0.1:9222
```

I suggest describing tags via Extra parameter when we create a subscription:

``` erlang
exometer_report:subscribe(Reporter, [eradius, '127.0.0.1:8111', requests], value, 500, [{nas, {from_name, 2}}], true).
```

It means "create a tag called nas from the second element of name and remove it from the name"

This solution works well in exometer infrastructure and has backward compatibility.

**Comment by GalaxyGorilla** [comment]
I generally like this solution. In case of a generic metric configuration one needs to standardize the shape of the metric IDs, e.g. something like: [name_part1, name_part2, tag1, tag2]. This is the prize for this feature, I see no better solution. 

(Btw you mean [eradius, '127.0.0.1:8111', requests] instead of just '127.0.0.1:8111' right?)

**Comment by surik** [comment]
@GalaxyGorilla yes, thx. updated
